//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS_WebAppWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Subject()
        {
            this.ExaminationSchedules = new HashSet<ExaminationSchedule>();
        }
    
        public System.Guid SubjectId { get; set; }
        public string SubjectName { get; set; }
        public System.Guid ClassId { get; set; }
        public System.Guid StaffId { get; set; }
        public System.Guid CustomerId { get; set; }
        public System.DateTime AddedOn { get; set; }
        public System.Guid AddedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public bool Status { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExaminationSchedule> ExaminationSchedules { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
