//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS_WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Designation
    {
        public System.Guid DesignationId { get; set; }
        public string DesignationName { get; set; }
        public System.DateTime DesignationEffectiveFrom { get; set; }
        public Nullable<System.DateTime> DesignationEffectiveTo { get; set; }
        public System.Guid CustomerId { get; set; }
        public System.DateTime AddedOn { get; set; }
        public System.Guid AddedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public bool Status { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
