//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS_WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExaminationSchedule
    {
        public System.Guid ExaminationScheduleId { get; set; }
        public System.Guid ExaminationTypeId { get; set; }
        public System.Guid SubjectId { get; set; }
        public System.Guid ClassId { get; set; }
        public System.Guid HallId { get; set; }
        public System.Guid InvigilatorId { get; set; }
        public System.Guid HandlingStaffId { get; set; }
        public System.DateTime ExaminationDate { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public System.Guid CustomerId { get; set; }
        public System.DateTime AddedOn { get; set; }
        public System.Guid AddedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public bool Status { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Class Class1 { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual ExaminationType ExaminationType { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual Staff Staff1 { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
