//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS_WebAppEFV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionPaper
    {
        public System.Guid QuestionPaperId { get; set; }
        public string SubjectName { get; set; }
        public System.TimeSpan duration { get; set; }
        public int totalmarks { get; set; }
        public System.Guid CustomerId { get; set; }
        public System.DateTime AddedOn { get; set; }
        public System.Guid AddedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public bool Status { get; set; }
        public string questionpaperdata { get; set; }
        public System.Guid ExaminationTypeId { get; set; }
        public string ExaminationType { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
